name: Update Last.fm

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch latest track
        run: |
          DATA=$(curl -s "https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=Sallytion&api_key=904ca22dbf1db0912ec47c341056ddad&format=json&limit=1")

          echo "$DATA" > debug.json

          NAME=$(jq -r '.recenttracks.track[0].name' debug.json)
          ARTIST=$(jq -r '.recenttracks.track[0].artist["#text"]' debug.json)
          NOWPLAYING=$(jq -r '.recenttracks.track[0]["@attr"].nowplaying // "false"' debug.json)

          if [ "$NOWPLAYING" = "true" ]; then
            TEXT="🟢 Now Playing: $NAME - $ARTIST"
          else
            TEXT="⏸️ Last Played: $NAME - $ARTIST"
          fi

          echo "$TEXT" > lastfm.txt
          echo "OUTPUT: $TEXT"

      - name: Update README safely
        run: |
          NEW=$(cat lastfm.txt)

          awk -v new="$NEW" '
          /<!-- LASTFM -->/ { print; print new; skip=1; next }
          /<!-- END -->/ { skip=0 }
          !skip
          ' README.md > temp.md

          mv temp.md README.md

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add README.md

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "Update Last.fm"
          git push
